name: FTP Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # (Opcional) Build steps se necessário
    - name: Build project
      run: |
        npm install
        npm run build
    
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.portalwebpe.com.br
        username: pwpecombr
        password: K!ko3009
        port: 21
        local-dir: ./src  # Diretório atual do projeto
        server-dir: /home2/pwpecombr/dev.portalwebpe.com.br/
        # Opções adicionais úteis:
        dangerous-clean-slate: false  # Não apagar tudo no servidor
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/