name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo Building the project

    deploy-development:
        runs-on: ubuntu-latest
        environment:
            name: development
            url: http://dev.portalwebpe.com.br
        needs: build
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v1
            - name: Hostgagot Development
              uses: easinger/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.DEV_HOSTGATOR_PUB }}
                  ARGS: "-rlgoDzvC --delete"
                  SOURCE: "src/"
                  REMOTE_HOST: "portalwebpe.com.br"
                  REMOTE_USER: "pwpecombr"
                  REMOTE_PORT: "22"
                  TARGET: "/home/pwpecombr/public_html/dev.portalwebpe.com.br/"