name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo Building the project

    deploy-development:
        runs-on: ubuntu-latest
        environment:
            name: development
            url: http://dev.portalwebpe.com.br
        needs: build
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v1
            - name: Hostgator Development
              uses: appleboy/scp-action@v0.1.7
              with:
                  host:  portalwebpe.com.br
                  username: pwpecombr
                  key: ${{ secrets.DEV_HOSTGATOR_PUB }}
                  port: 22
                  source: "src/*"
                  target: "/home/pwpecombr/public_html/dev.portalwebpe.com.br/"
                  rm: true