name: "Deploy website on MAIN"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./src
        run: npm ci

      - name: Build assets
        working-directory: ./src
        run: npm run build

      - name: Ensure production mode
        run: |
          rm -f ./src/public/hot
          rm -rf ./src/node_modules

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USER }}
          password: ${{ vars.FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: /dev.portalwebpe.com.br/
          exclude: |
            **/.git*/**
            node_modules/**
            **/node_modules/**
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
